name: SurvivalKits
version: 1.0.0
main: SurvivalKits\Main
api: 5.0.0
author: gabriqlna
softdepend: [FormAPI, PlaceholderAPI, PurePerms, ScoreHud]
depend: [PlaceholderAPI]

commands:
  kit:
    description: "Abre o menu de kits ou resgata um kit direto"
    usage: "/kit [nome]"
    aliases: ["kits"]
    permission: survivalkits.command

permissions:
  survivalkits.command:
    description: "Permite usar o comando base /kit"
    default: true

  # Abaixo registramos as permiss천es que ser찾o usadas nos kits do config.yml
  kit.membro:
    description: "Permiss찾o para acessar o kit Membro"
    default: true

  kit.vip:
    description: "Permiss찾o para acessar o kit VIP"
    default: op

